### ISSUE TITLE
summary refreshing

### ISSUE THREAD

**Issue by valzak74** [NonFactors/Wellidate#5]
Hi, thx for your wonderful software.

I'm trying to check "remote" rule and it get class = "input-validation-error" for my testing input html tag by this:
rule....
remote...
    apply(validatable, response) {
                    validatable.error("remote", result.message);
                }
I see my input is incorrect (red bordered) but the summary doesn't changed.
I think that is because time delay between start of validation and getting result from remote url.
How can i fix it?
Regards, Valentin.

**Comment by valzak74** [comment]
also all API calls like form() or validate() return true even if remote rule returning error

**Comment by Muchiachio** [comment]
Yes, because remote calls are asynchronous and can't stop the execution of form or validate to return "the end result".
The same problem affects the summary, the only workaround now would be to append the error from the remote rule itself.

We will think about the temporary solution, if it's even possible for synchronous code. As a normal solution would need promise based solution, which is a breaking change compared to original jQuery validate library.

**Comment by Muchiachio** [comment]
The issue with summary not updating is fixed.
You can also stop form from submitting by inspecting for pending results in `submitHandler`.
Validation results from `validate` function now include `pending` array which can be checked or awaited on user side if needed.
